// Audio manifest for the Ninja Adventure pack (CC0, by Pixel-boy & AAA).
//
// Sources used (pack folder Audio/):
//   Musics/   31 - Sunny, 22 - Dream, 1 - Adventure Begin, 34  - Fight   (4 of 41 .ogg)
//   Jingles/  Success3, Secret2                                          (2 of 15 .wav)
//   Sounds/   Menu, Hit & Impact, Whoosh & Slash, Elemental, Alert, Magic & Skill,
//             Bonus, Creature, Ambient                                  (20 of 132 .wav)
// Deliberately skipped: Voice/ (vocal grunts), Jump & Bounce/ (platformer), Rain/Storm/Wave
// ambiences, the GameOver/LevelUp jingles (MUSIC has a fixed key set; LevelUp jingles are
// 1.2-2 s and would break the <=1 s SFX rule - PowerUp1 stands in), Explosion*/Fire*/Magic
// spell FX (no spell system yet), and the remaining 37 music tracks.
//
// Files live flat in /public/game/audio/ under their ORIGINAL basenames (spaces included;
// '34  - Fight' really has two spaces). Every clip ships in two containers:
//   .m4a  AAC-LC via afconvert. `-b 96000` (music) / `-b 128000` (SFX, jingles) are TARGETS; the
//         encoder's measured stream rate (afinfo) is 82-94 kbps for the music and 53-96 kbps for
//         the short/simple clips, and is quoted per clip below. Plays in every current browser.
//   .ogg  music: the untouched Vorbis original (Chrome/Firefox, gapless HTMLAudioElement loops).
//         jingles: a Vorbis encode of the pack wav via libsndfile (default quality), so every MUSIC
//         entry has a non-AAC container too (the two jingles have no ogg in the pack).
//   .wav  SFX: byte-identical pack originals (PCM_16 44.1 kHz stereo) EXCEPT three that are
//         conditioned with soundfile because they cannot work as shipped (footstepGrass, windLoop, riverLoop;
//         exact operations in their comments and in scratchpad/catalogue/audio_manifest.json).
//         All one-shots are < 1 s so none needed trimming.
// Format pick: `new Audio().canPlayType('audio/mp4; codecs="mp4a.40.2"')` -> m4a, else ogg/wav.
// Looping:
//   * windLoop / riverLoop are seamless BY CONSTRUCTION (self-crossfaded, first and last 50 ms within
//     0.5 dB, sample-continuous wrap): loop them with AudioBufferSourceNode.loop = true, or an
//     HTMLAudioElement on the .wav. Do NOT loop the .m4a through an HTMLAudioElement: AAC carries
//     2112 samples (48 ms) of encoder priming that only decodeAudioData trims (Web Audio), so that path gaps.
//   * overworld / battle loop seamlessly (head/tail within 2-5 dB, wrap steps <= -28 dBFS).
//   * title has a -21 dBFS sample step at the wrap (cut mid-waveform): see its comment for the
//     measured loopEnd fix; overworldNight is a composed fade-out then a 21 dB re-entry - a
//     restart, not a cycle; both are documented, neither can be fixed without re-encoding the ogg.
// Levels: `volume` = 10^((roleTarget - measuredRMS)/20) clamped to [0.05, 1], from the RMS of the
// SHIPPED primary file, so at master 1.0: music -24 dBFS RMS (night -26, battle -23), UI -24,
// footsteps -30 (both, matched), ambience -36. Entries whose source is too quiet to reach the
// target at 1.0 say so in their comment (all pack SFX peak at -10 dBFS, so there is no headroom).
// Every number in the comments is measured with soundfile/numpy (and afinfo) over the shipped files.
// To feed the contract's AudioClip: { url: canAac ? t.m4a : (t.ogg ?? t.wav), volume: t.volume, loop: t.loop }.
// Generated by scratchpad/catalogue/build_audio.py - edit that, not this.

export type MusicKey = 'overworld' | 'overworldNight' | 'title' | 'battle' | 'victory' | 'item';

/** A music track or jingle. `ogg` is optional in the contract but present for all six entries. */
export interface MusicTrack { ogg?: string; m4a: string; loop: boolean; volume: number }

/** A one-shot (or, when `loop` is true, a seamless bed) sound effect. */
export interface SfxClip { m4a: string; wav: string; volume: number; loop?: boolean }

export const MUSIC = {
  // 31 - Sunny.ogg: 69.8 s, -17.8 dB RMS, peak -4.4 dB, lands at -24.0 dB; ogg 1659 KiB + m4a 820 KiB (94 kbps).
  // Why: 110 bpm, mid-bright (centroid 2.7 kHz), 70 s; seamless loop (first/last 50 ms -19.5/-20.1 dB, wrap step -30 dBFS); brightest of the calm candidates without being harsh. Calm Village (80 bpm) and Village (105 s, 3.4 MB) read as town themes; Chill and Good Time fade/are quieter.
  overworld: { ogg: '/game/audio/31 - Sunny.ogg', m4a: '/game/audio/31 - Sunny.m4a', loop: true, volume: 0.49 },
  // 22 - Dream.ogg: 96.0 s, -25.0 dB RMS, peak -4.0 dB, lands at -26.0 dB; ogg 2279 KiB + m4a 1113 KiB (93 kbps).
  // Why: quietest candidate (-25.0 dB RMS), 96 s, 105 bpm, centroid 2.1 kHz. NOT a seamless cycle: the track ends on a composed fade (last 3 s -28.4, last 1 s -34.7, last 50 ms -38.8 dB) and re-enters at -17.9 dB, a 21 dB step every 96 s - a fade-out-then-restart, which is acceptable for a night bed. '13 - Mystical' is no better (tail 7 dB louder than its head). If a truly seamless cycle matters more than the mood, '27 - Chill' (48 s, -24.8 dB, dark 1.7 kHz, 2 dB step across the seam at 1 s scale) is the drop-in swap.
  overworldNight: { ogg: '/game/audio/22 - Dream.ogg', m4a: '/game/audio/22 - Dream.m4a', loop: true, volume: 0.89 },
  // 1 - Adventure Begin.ogg: 82.3 s, -15.5 dB RMS, peak 0.3 dB, lands at -23.9 dB; ogg 1628 KiB + m4a 967 KiB (94 kbps).
  // Why: 82 s, 105 bpm; loops musically (head 1 s -17.4 / tail 1 s -15.0 dB) but the file is cut mid-waveform: last sample L -0.089 vs first sample 0.000 = a -21 dBFS step at the wrap, and the first 50 ms are 8 dB louder than the last 50 ms. Both channels pass within 0.005 of zero 1.32 ms before the end, so with Web Audio set loopEnd = duration - 0.0013 s (or ramp a GainNode 0->1 over 3 ms on restart); an HTMLAudioElement loop cannot do either and the tick is masked by the downbeat that follows. '35 - Adventure' has a composed ending (tail -30 dB) and is 2x the bytes. Loudest track in the pack (-15.5 dB) hence the low volume.
  title: { ogg: '/game/audio/1 - Adventure Begin.ogg', m4a: '/game/audio/1 - Adventure Begin.m4a', loop: true, volume: 0.38 },
  // 34  - Fight.ogg: 96.0 s, -18.7 dB RMS, peak -1.5 dB, lands at -23.0 dB; ogg 2995 KiB + m4a 982 KiB (82 kbps).
  // Why: 178 bpm like '17 - Fight' but 96 s instead of 32 s (less repetitive in long fights), 5 dB hotter with peaks at -1.5 dB; seamless loop (head/tail 1 s -19.0/-18.1 dB, wrap step -28 dBFS). NOTE: the original filename has TWO spaces before the dash.
  battle: { ogg: '/game/audio/34  - Fight.ogg', m4a: '/game/audio/34  - Fight.m4a', loop: true, volume: 0.61 },
  // Success3.wav: 2.0 s, -28.6 dB RMS, peak -10.0 dB, lands at -28.6 dB; ogg 32 KiB + m4a 28 KiB (96 kbps).
  // Why: longest full fanfare of the Success set (2.0 s), brightness rises 3.6 -> 4.8 kHz across the clip (triumphant), ends at -43 dB. Volume clamped at 1.0: lands at -28.6 dB, 4.6 dB under the -24 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  victory: { ogg: '/game/audio/Success3.ogg', m4a: '/game/audio/Success3.m4a', loop: false, volume: 1.0 },
  // Secret2.wav: 1.6 s, -25.7 dB RMS, peak -10.0 dB, lands at -25.7 dB; ogg 25 KiB + m4a 23 KiB (95 kbps).
  // Why: 'Secret' = discovery chime; 1.55 s, resolves upward (2.2 -> 2.9 kHz), ends clean (-35 dB). Shorter than Secret1/3 so it does not stall play. Volume clamped at 1.0: lands at -25.7 dB, 1.7 dB under the -24 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  item: { ogg: '/game/audio/Secret2.ogg', m4a: '/game/audio/Secret2.m4a', loop: false, volume: 1.0 },
} satisfies Record<MusicKey, MusicTrack>;

export const SFX = {
  // Move6.wav: 0.18 s, -20.8 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 31 KiB + m4a 6 KiB (68 kbps).
  // Why: 0.18 s single crisp blip (4.6 kHz), -20.8 dB, fully tonal (flatness 0.000); loudest/cleanest of the Move set.
  cursorMove: { m4a: '/game/audio/Move6.m4a', wav: '/game/audio/Move6.wav', volume: 0.69 },
  // Move2.wav: 0.10 s, -25.2 dB RMS, peak -10.0 dB, lands at -28.1 dB; wav 18 KiB + m4a 5 KiB (71 kbps).
  // Why: shortest file in the pack (0.10 s), soft (-25 dB), decays 27 dB within the clip: a typewriter tick.
  textBlip: { m4a: '/game/audio/Move2.m4a', wav: '/game/audio/Move2.wav', volume: 0.72 },
  // Accept9.wav: 0.32 s, -23.9 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 54 KiB + m4a 8 KiB (78 kbps).
  // Why: two-note rising confirm: centroid 2.4 -> 3.7 -> 4.2 kHz, 0.31 s.
  confirm: { m4a: '/game/audio/Accept9.m4a', wav: '/game/audio/Accept9.wav', volume: 0.99 },
  // Cancel2.wav: 0.31 s, -26.9 dB RMS, peak -10.0 dB, lands at -26.9 dB; wav 54 KiB + m4a 8 KiB (77 kbps).
  // Why: falling pitch (3.8 -> 3.1 kHz), 0.31 s, softer than Cancel.wav (0.47 s). Volume clamped at 1.0: lands at -26.9 dB, 2.9 dB under the -24 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  cancel: { m4a: '/game/audio/Cancel2.m4a', wav: '/game/audio/Cancel2.wav', volume: 1.0 },
  // Hit8.wav: 0.40 s, -24.8 dB RMS, peak -10.0 dB, lands at -26.0 dB; wav 70 KiB + m4a 9 KiB (87 kbps).
  // Why: lowest-pitched tonal hit in the pack (200 Hz f0, centroid 1.7 kHz), 0.40 s, -24.8 dB. Soft onset: -12 dB at 56 ms, peak at 125 ms - fire it on the first blocked frame and rate-limit (~250 ms). Every snappier candidate is either a bright tick (Hit9, 2.7 kHz) or a rising boing (Bounce2/Jump3).
  bump: { m4a: '/game/audio/Hit8.m4a', wav: '/game/audio/Hit8.wav', volume: 0.87 },
  // Whoosh2.wav: 0.44 s, -27.2 dB RMS, peak -10.0 dB, lands at -27.2 dB; wav 76 KiB + m4a 7 KiB (53 kbps).
  // Why: noise-based air swish (flatness 0.07, the noisiest non-slash clip), 0.44 s: a sliding shoji/wooden door. Whoosh.wav is 5 dB softer and more tonal. Volume clamped at 1.0: lands at -27.2 dB, 3.2 dB under the -24 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  doorOpen: { m4a: '/game/audio/Whoosh2.m4a', wav: '/game/audio/Whoosh2.wav', volume: 1.0 },
  // Grass.wav: 0.36 s, -25.9 dB RMS, peak -10.0 dB, lands at -30.1 dB; wav 62 KiB + m4a 8 KiB (78 kbps).
  // Why: bright rustle (6.2 kHz, flatness 0.067) that swells to its peak at 160 ms (a brush through grass); Grass2 peaks sooner but is 9 dB quieter still. The source is a mastering outlier (peak -22.6 dBFS where 105/132 pack SFX peak at -10.0), so the shipped wav is peak-normalised to -10.0 dBFS (+12.6 dB, exact gain, no limiting) and the m4a is encoded from that - otherwise it could not reach the footstep target at volume <= 1. Level-matched to footstepSand: both land at -30.0 dB RMS. CONDITIONED: peak-normalised -22.6 -> -10.0 dBFS (x4.28, +12.6 dB) (source was 0.36 s, -38.5 dB RMS, peak -22.6 dB).
  footstepGrass: { m4a: '/game/audio/Grass.m4a', wav: '/game/audio/Grass.wav', volume: 0.62 },
  // Impact4.wav: 0.29 s, -22.8 dB RMS, peak -10.0 dB, lands at -29.9 dB; wav 51 KiB + m4a 7 KiB (71 kbps).
  // Why: instant attack (-12 dB at 1 ms, peak at 44 ms), a 133 Hz thump under noisy crunch (flatness 0.062), 0.29 s: a sand/gravel scuff. Launch.wav (bodiless 5 kHz puff) was the runner-up. Level-matched to footstepGrass: both land at -30.0 dB RMS.
  footstepSand: { m4a: '/game/audio/Impact4.m4a', wav: '/game/audio/Impact4.wav', volume: 0.44 },
  // Alert.wav: 0.49 s, -24.1 dB RMS, peak -10.0 dB, lands at -24.1 dB; wav 85 KiB + m4a 10 KiB (92 kbps).
  // Why: 0.49 s sustained 3.1 kHz beep-beep (steady -23 dB for three quarters then decay); Alert5 (1.5 s siren) is too long, Alert2 is a low 1 kHz tone. Volume clamped at 1.0: lands at -24.1 dB, 4.1 dB under the -20 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  encounterAlert: { m4a: '/game/audio/Alert.m4a', wav: '/game/audio/Alert.wav', volume: 1.0 },
  // Impact.wav: 0.24 s, -16.2 dB RMS, peak -10.0 dB, lands at -19.9 dB; wav 41 KiB + m4a 7 KiB (86 kbps).
  // Why: shortest (0.24 s) and second-loudest impact (-16.2 dB), centroid falls 3.9 -> 2.8 kHz: a solid punch.
  attackHit: { m4a: '/game/audio/Impact.m4a', wav: '/game/audio/Impact.wav', volume: 0.65 },
  // Sword2.wav: 0.21 s, -20.1 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 37 KiB + m4a 6 KiB (58 kbps).
  // Why: 0.21 s blade swish, noisy (flatness 0.19), 6.9 kHz; extra for melee animations.
  attackSwing: { m4a: '/game/audio/Sword2.m4a', wav: '/game/audio/Sword2.wav', volume: 0.64 },
  // Magic4.wav: 0.55 s, -22.0 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 95 KiB + m4a 10 KiB (77 kbps).
  // Why: descending low tone (1.1 kHz -> 0.8 kHz, overall centroid 686 Hz = darkest clip in the pack), 0.55 s: a power-down/defeat.
  faint: { m4a: '/game/audio/Magic4.m4a', wav: '/game/audio/Magic4.wav', volume: 0.79 },
  // PowerUp1.wav: 0.47 s, -23.1 dB RMS, peak -10.0 dB, lands at -23.1 dB; wav 81 KiB + m4a 9 KiB (72 kbps).
  // Why: rising sweep 1.5 -> 2.7 kHz over 0.47 s, tonal; LevelUp jingles are 1.2-2 s and would violate the 1 s SFX cap. Volume clamped at 1.0: lands at -23.1 dB, 1.1 dB under the -22 target (the source peaks at the pack's -10 dBFS ceiling, so no headroom is left).
  levelUp: { m4a: '/game/audio/PowerUp1.m4a', wav: '/game/audio/PowerUp1.wav', volume: 1.0 },
  // Coin.wav: 0.29 s, -17.1 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 50 KiB + m4a 6 KiB (56 kbps).
  // Why: 0.29 s bright coin ping (4.4 kHz), loudest bonus sound (-17 dB); extra.
  coin: { m4a: '/game/audio/Coin.m4a', wav: '/game/audio/Coin.wav', volume: 0.45 },
  // Heal.wav: 0.31 s, -23.3 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 54 KiB + m4a 7 KiB (77 kbps).
  // Why: 0.31 s soft chime (1.9 kHz); extra.
  heal: { m4a: '/game/audio/Heal.m4a', wav: '/game/audio/Heal.wav', volume: 0.92 },
  // Water4.wav: 0.41 s, -22.3 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 71 KiB + m4a 8 KiB (79 kbps).
  // Why: strong attack then 0.3 s decay (quarters -17/-25/-31/-52 dB), 0.41 s; the Water set is all tonal 'bloops', this one has the most splash-like envelope.
  splash: { m4a: '/game/audio/Water4.m4a', wav: '/game/audio/Water4.wav', volume: 0.82 },
  // Bird.wav: 0.16 s, -27.3 dB RMS, peak -10.0 dB, lands at -28.0 dB; wav 28 KiB + m4a 6 KiB (75 kbps).
  // Why: only bird clip: 0.16 s, 6.8 kHz.
  birdChirp: { m4a: '/game/audio/Bird.m4a', wav: '/game/audio/Bird.wav', volume: 0.92 },
  // Dog.wav: 0.27 s, -22.4 dB RMS, peak -10.0 dB, lands at -24.0 dB; wav 46 KiB + m4a 7 KiB (80 kbps).
  // Why: only dog clip: 0.27 s, 2.4 kHz.
  dogBark: { m4a: '/game/audio/Dog.m4a', wav: '/game/audio/Dog.wav', volume: 0.83 },
  // Wind2.wav: 14.90 s, -21.7 dB RMS, peak -10.0 dB, lands at -36.1 dB, first/last 50 ms -22.6/-22.5 dB, wrap step -52.5 dBFS; wav 2567 KiB + m4a 237 KiB (126 kbps).
  // Why: the only usable wind bed (Wind.wav is -49 dB with a 1 s silent lead). The source is authored with a 0.3 s fade-in and a ~2 s fade-out (first/last 50 ms -44.6/-32.0 dB against a -22 dB body), so a plain loop=true would dip ~12 dB every cycle; the shipped wav is CONDITIONED into a seamless loop - fades trimmed, then the last 2 s equal-power crossfaded onto the first 2 s - so loop=true is gapless on any sample-accurate player. CONDITIONED: trimmed 0.30 s head / 2.0 s tail, last 2 s equal-power crossfaded onto first 2 s -> 14.90 s seamless loop (source was 19.20 s, -22.0 dB RMS, peak -10.0 dB).
  windLoop: { m4a: '/game/audio/Wind2.m4a', wav: '/game/audio/Wind2.wav', volume: 0.19, loop: true },
  // River.wav: 14.60 s, -35.7 dB RMS, peak -14.0 dB, lands at -36.0 dB, first/last 50 ms -39.8/-39.3 dB, wrap step -52.9 dBFS; wav 2515 KiB + m4a 233 KiB (126 kbps).
  // Why: the only river bed in the pack. The source opens with 46 ms of digital silence + a 0.6 s fade-in and closes with a ~2 s fade-out (first/last 50 ms -72.8/-51.9 dB against a -35.8 dB body), so a plain loop=true would produce an audible dropout every cycle; the shipped wav is CONDITIONED the same way (trim + 2 s equal-power self-crossfade) into a seamless loop. CONDITIONED: trimmed 0.60 s head / 2.0 s tail, last 2 s equal-power crossfaded onto first 2 s -> 14.60 s seamless loop (source was 19.20 s, -35.8 dB RMS, peak -12.7 dB).
  riverLoop: { m4a: '/game/audio/River.m4a', wav: '/game/audio/River.wav', volume: 0.97, loop: true },
} satisfies Record<string, SfxClip>;

export const CREDITS =
  'Music and sound effects from the "Ninja Adventure" asset pack by Pixel-boy and AAA (Pixel Archipel), ' +
  'released under CC0 1.0 (public domain). https://pixel-boy.itch.io/ninja-adventure-asset-pack';
